#! /bin/sh

# Starting sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Basic settings
bspc monitor -d I II III IV V
# two monitor stuff
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-0')
if [[ $my_laptop_external_monitor = *connected* ]]
then
	bpsc monitor DP-2 -r 
	bspc monitor HDMI-0 -d I II III IV V 
fi
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# Border
bspc config border_width 2
bspc config window_gap 5

bspc config focused_border_color        "#83a598"
bspc config normal_border_color         "#665c54"
bspc config active_border_color         "#665c54"

# Space on top for polybar
bspc config top_padding 25

#
# Autostart
#

# Notifications
/home/piotr/.config/dunst/launch.sh &

# Wallpaper
feh --bg-fill /walls/gruvpacman.png &

# Picom
picom --experimental-backend &

# Flameshot
flameshot &

#Bar
sh ~/.config/polybar/launch.sh &

# Network Applet
nm-applet --indicator &

# Bluetooth Applet
blueberry-tray &
